version: '3'
services:
  tpcds:
    build: .
    container_name: "tpcds"
    stdin_open: true
    tty: true
    entrypoint: bash
    volumes:
      - tpcds-vol:/root/tpcds-kit
    env_file: .env

  # example postgreSQL database
  psql:
    container_name: psql
    image: postgres
    ports:
      - 30000:5432
    volumes:
      - psql-vol:/var/lib/postgresql/data
    env_file: .env

volumes:
  tpcds-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/tpcds-vol/tpcds
  
  psql-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/tpcds-vol/psql